### ISSUE TITLE
Strange auto-indent after semi-colon

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASQE-deprecated#104] opened 2017-05-11 11:10 UTC
When pressing `RET' after the semi-colon, I expect auto-indentation to indent (1) to the same indentation level of the previous line (2 space in this case), or (2) to the same indentation level of the previous line plus a fixed amount (e.g., 4 spaces in this case).  A third option (3) might be to indent to the column at which the predicate of the previous line starts (18 spaces in this case), but this is probably not a good idea because the indentation becomes very unregular WRT other parts of the query.

What currently happens is that auo-indentation moves to column 54 or something, probably trying to align with the end-of-statement character from the previous line (see the `<HERE>` pointer in the query string below).

```sparql
prefix bag: <http://lod.geodan.nl/vocab/bag#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?wkt ?wktLabel {
  ?openbareRuimte bag:naamOpenbareRuimte "'t Spiker" ;
                                                     <HERE>
```

**Comment by wouterbeek** [comment] 2017-05-11 11:17
PS: I can confirm that YASQE does try to implement auto-completion variant (3) described by me in the issue.

**Comment by LaurensRietveld** [comment] 2020-01-13 13:25
This* is fixed in the latest release (see https://github.com/TriplyDB/Yasgui and https://yasgui.triply.cc)

*) There are other indentation issues. But this one I can't reproduce in the new version

**Closed as completed by LaurensRietveld** 2020-01-13 13:25 UTC
Labels: bug
