### ISSUE TITLE
YASQE freezes browser in certain situation

### ISSUE THREAD

**Issue by gneissone** [Triply-Dev/YASGUI.YASQE-deprecated#135] opened 2018-06-26 16:39 UTC
My browser freezes on the SPARQL query page in the UI in a very specific situation...

I experience the issue when the last prefix in the query is on the same line as the beginning of the SELECT or CONSTRUCT statement, then try to add a new triple to the query containing a prefix not already in the prefixes list. 

The query page tries to add the new prefix to the prefixes list at the top, but my browser locks up in the situation described above. It works fine if the last prefix statement and the beginning of the SELECT or CONSTRUCT is on a new line.

<img width="957" alt="screen shot 2018-06-22 at 1 09 32 pm" src="https://user-images.githubusercontent.com/10748475/41926626-1dd209f8-792d-11e8-8e15-1a46e1884e35.png">

**Comment by wouterbeek** [comment] 2018-06-26 17:15
I've observed similar slowdowns with longer lines.  A quick fix would be to separate the various prefix declarations by newlines.  The real solution is to critically inspect the YASQE parser, which I suspect uses unnecessary per-line processing in some places.

**Comment by gneissone** [comment] 2018-06-26 17:26
To clarify, the issue I'm describing occurs at any line length if the last prefix and the beginning of the query itself are on the same line. Another example from the demo site:

![Another example](https://user-images.githubusercontent.com/10748475/41928826-b5eca800-7933-11e8-977b-7ff96d0945f3.png)

**Comment by LaurensRietveld** [comment] 2018-06-27 06:13
Thanks for the report @gneissone . This was caused by yasqe creating an invalid query as it auto-inserted the foaf prefix at the wrong location. Fixed by simply prepending the new prefix declaration at the top of the query, instead of just before the select

**Closed as completed** 2018-06-27 06:13 UTC
