### ISSUE TITLE
Using with React?

### ISSUE THREAD

**Issue by YanDoroshenko** [Triply-Dev/YASGUI.YASQE-deprecated#136] opened 2018-07-13 17:34 UTC
Is there a way to use YASQE from a React environment?

**Comment by LaurensRietveld** [comment] 2018-07-16 06:40
There shouldnt be any limitation on using it in a react environment. Some thoughts:
- If you have server-side rendering, you should exclude the YASQE package from being rendered on the server (the main dependency of yasqe, codemirror, requires a `document` and `window` reference, that won't be there in nodejs)
- You'd probably need to draw an empty div in your `render` function, and and a `ref` to it. That way, you can use that div as argument when instantiating yasqe (something like `<div ref={el => (this.yasguiWrapper = el)}/>`
- You should probably add the yasqe initialization to the `componentDidMount` lifecycle method
- You _might_ need to add a `this.yasqe.refresh()` in the `componentDidUpdate` lifecycle method (changing other parts in the component, or e.g. navigating back and forth in your react app, might result in a gray yasqe query area. I think this is caused by codemirror that applies some JS magic to draw position some elements. A `yasqe.refresh` would fix this).

Closing this, but let me know how it goes

**Closed as completed by LaurensRietveld** 2018-07-16 06:40 UTC

**Comment by YanDoroshenko** [comment] 2018-07-16 08:18
I managed to add a normal textarea and then to do a `YASQE.fromTextArea(e.target).setValue(value)` to create an editor from it on focus. Seems to work alright. Thanks.

**Comment by YanDoroshenko** [comment] 2018-07-16 09:23
@LaurensRietveld One more question - is there a way to add a change listener to the editor? I need to notify other components every time the value of the editor changes.

**Comment by LaurensRietveld** [comment] 2018-07-16 11:08
Yasqe extends the codemirror functionality (see https://codemirror.net/doc/manual.html). Some functionality that codemirror offers is the on change event (`yasqe.on('change', function(){})`). That should help you here

**Comment by YanDoroshenko** [comment] 2018-07-16 16:13
@LaurensRietveld Just what I needed! Awesome, thanks!

**Comment by jrenee42** [comment] 2019-03-27 14:46
@YanDoroshenko  please post a full example of how you got it working; thanks!

**Comment by YanDoroshenko** [comment] 2019-03-27 15:09
@jrenee42 Here you go:
```javascript
import YASQE from "yasgui-yasqe";

const yasqe = YASQE.fromTextArea(e.target);
yasqe.setValue(value);
yasqe.on('change', () => {
    props.onChange(yasqe.getValue());
});
```

**Comment by jrenee42** [comment] 2019-03-27 15:33
@YanDoroshenko  what is 'value' (setValue(value))

more context/more code please; the more the better!  (i am new to react)

**Comment by YanDoroshenko** [comment] 2019-03-27 17:38
@jrenee42 `setValue` is a method to set the value of the YASQE editor. `value` is just some local variable declared earlier. It has nothing to do with React.
I can't give you any more code or context as it was a part of a big framework and seeing the code would confuse you even more.
Try creating a textarea and then triggering the code I've written - initializing YASQE and such (I've done it on focus).

**Comment by jrenee42** [comment] 2019-03-27 18:49
thanks, i've since got it working.

**Comment by D063520** [comment] 2019-06-06 08:29
Hi @jrenee42,

I'm also struggeling with this, could you post your integration. For me it is not working currently ...

Currently I have this:

```
componentDidMount(){
       const s = document.createElement('script');
        s.src = "http://cdn.jsdelivr.net/npm/yasgui@2.7.29/dist/yasgui.min.js"; 
       this.instance.appendChild(s); 
      const s2 = document.createElement('script'); 
       s2.type = 'text/javascript'; 
      s2.innerHTML = "var yasgui = YASGUI(document.getElementById(\"showcase\"));"; 
}

render() { 
       return ( 
          <div > 
               <div ref={el => (this.instance = el)} > 
                    <div id='showcase'/> 
                </div>; 
            </div> 
        ); 
} 
 ```

But at runtime I get ReferenceError: Can't find variable: YASGUI

Thank you
D063520

**Comment by D063520** [comment] 2019-06-06 17:49
Hi,

this is my second version:

’’’
constructor(props) {
        super(props);
        var yasqe = null;
        var yasr = null;
    }

componentDidMount() {
        this.yasqe = YASQE.fromTextArea(document.getElementById("yasqe"), {
            sparql: {
                showQueryButton: true
            }
        });
        this.yasqe.refresh();
    }

    render() {
        console.log("Sparql endpoint");
        return (
            <div >
                <div>
                    <textarea id="yasqe"></textarea>
                    <div id="yasr"></div>
                </div>
            </div>
        );
    }
’’’

The problem here is that I get the gray area you described in the first post (even if I add  this.yasqe.refresh();). After expanding to full screen and expanding back it renders right. Any clue?
